import './global.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {cn} from "@/lib/utils"
import Navbar from '@/components/Navbar';
import Provider from '@/components/ui/Provider';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Abdullrahman_Project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className,'antialiased min-h-screen pt-5')
      
      }>
        <Provider>
        <Navbar/>
        {children}
        <Toaster/>
        </Provider>
        </body>
       
    </html>
  )
}
